name: practice_1
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/Maximov-Ivan/flutter_course_2024

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.2
  lakos: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
